<?php 
defined('SOURCE') or define('SOURCE', 'http://' . $_SERVER['SERVER_NAME'] . '/source');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>一叶知秋</title>
    <script src="http://g.alicdn.com/sj/lib/jquery/dist/jquery.min.js"></script>
    <script src="<?php echo SOURCE;?>/layer/layer.min.js"></script>
    <script src="http://cdnporch.qiniudn.com/echarts-all.js"></script>
    <!-- 使用 Amaze UI 前端框架 一下是引用的CSS和JS -->
    <link rel="stylesheet" href="http://cdn.amazeui.org/amazeui/2.0.0-beta1/css/amazeui.min.css">
    <script src="http://cdn.amazeui.org/amazeui/2.0.0-beta1/js/amazeui.min.js"></script>
    <script src="http://cdn.amazeui.org/amazeui/2.0.0-beta1/js/amazeui.legacy.min.js"></script>
    <script src="http://cdn.amazeui.org/amazeui/2.0.0-beta1/js/amazeui.widgets.helper.min.js"></script>
    <style>
    /*滚动条样式 仅支持Chrome*/
    html{
        overflow-y:scroll
    }
    ::-webkit-scrollbar{
        width:10px;
        height:10px
    }
    ::-webkit-scrollbar-button:vertical{
        display:none
    }
    ::-webkit-scrollbar-track:vertical{
        background-color:black
    }
    ::-webkit-scrollbar-track-piece{
        background:#fff
    }
    ::-webkit-scrollbar-thumb:vertical{
        background-color:#8E8E8E;
        border-radius:5px
    }
    ::-webkit-scrollbar-thumb:vertical:hover{
        background-color:#3B3B3B
    }
    ::-webkit-scrollbar-corner:vertical{
        background-color:#535353
    }
    ::-webkit-scrollbar-resizer:vertical{
        background-color:#FF6E00
    }
</style>
<script>
    var publicAlert = function(msg,status){
        if (!status) {
            layer.msg(msg, 2, -1);
        }else{
            layer.msg(msg, 2, status);
        }
    }
</script>
</head>
<body style="padding-right: 0px;">
    <?php echo $this ->getContent();?>
</body>
</html>